"""Add derived dags table

Revision ID: e4bbb5a200bb
Revises: 
Create Date: 2021-12-24 13:10:59.446532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e4bbb5a200bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'derived_pipelines',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('dag_id', sa.String(length=255), nullable=True),
        sa.Column('type', sa.Enum('sql', name='derivedpipelinetypes'), nullable=False),
        sa.Column('schedule', sa.String(length=50), nullable=True),
        sa.Column('schema_name', sa.String(length=63), nullable=False),
        sa.Column('table_name', sa.String(length=63), nullable=False),
        sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('enabled', sa.Boolean(), nullable=True),
        sa.Column('deleted', sa.Boolean(), nullable=True),
        sa.Column('created', sa.DateTime(), nullable=True),
        sa.Column('modified', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        schema='derived_dags_plugin',
    )
    # op.execute('alter table derived_pipelines owner to root')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('derived_pipelines', schema='derived_dags_plugin')
    op.execute('drop type derivedpipelinetypes')
    # ### end Alembic commands ###
