"""Add named cursor flag

Revision ID: f61343401db3
Revises:
Create Date: 2022-02-07 15:54:32

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f61343401db3'
down_revision = 'e4bbb5a200bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'derived_pipelines',
        sa.Column('use_named_cursor', sa.Boolean(), nullable=True),
        schema='derived_dags_plugin',
    )
    op.execute("UPDATE derived_dags_plugin.derived_pipelines SET use_named_cursor=TRUE")
    op.alter_column(
        'derived_pipelines', 'use_named_cursor', nullable=False, schema='derived_dags_plugin'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('derived_pipelines', 'use_named_cursor', schema='derived_dags_plugin')
    # ### end Alembic commands ###
